service: ias-server  

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20230521'
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - arn:aws:dynamodb:us-east-1:{credencials}:table/ProductTable
                
functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events:
      - http:
          path: /product
          method: post
  fetchItems:
    handler: src/fetchItems.handler
    events:
      - http:
          path: /products
          method: get
  fetchItem:
    handler: src/fetchItem.handler
    events:
      - http:
          path: /product/{id}
          method: get
  updateItem:
    handler: src/updateItem.handler
    events:
      - http:
          path: /products/{id}
          method: put
resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: ProductTable
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
